/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'title' : string,
  'summary' : string,
  'timestamp' : bigint,
}
export type LectureId = string;
export interface LectureRecord {
  'id' : LectureId,
  'qa' : Array<QA>,
  'url' : string,
  'title' : string,
  'thumbnailUrl' : string,
  'takeaways' : Array<string>,
  'createdAt' : bigint,
  'summary' : string,
  'transcript' : Array<TranscriptSegment>,
  'tableOfContents' : Array<Chapter>,
}
export interface QA {
  'id' : string,
  'question' : string,
  'createdAt' : bigint,
  'answer' : string,
  'timestamp' : [] | [bigint],
}
export interface TranscriptSegment { 'text' : string, 'timestamp' : bigint }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addQuestion' : ActorMethod<[LectureId, string, [] | [bigint]], string>,
  'askQuestion' : ActorMethod<
    [LectureId, string, [] | [bigint]],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteLecture' : ActorMethod<[LectureId], boolean>,
  'downloadNotes' : ActorMethod<[LectureId], [] | [string]>,
  'getLecture' : ActorMethod<[LectureId], [] | [LectureRecord]>,
  'getLectures' : ActorMethod<[], Array<LectureRecord>>,
  'processLecture' : ActorMethod<
    [string],
    { 'ok' : LectureRecord } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];