/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LectureId = IDL.Text;
export const QA = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'createdAt' : IDL.Int,
  'answer' : IDL.Text,
  'timestamp' : IDL.Opt(IDL.Nat),
});
export const TranscriptSegment = IDL.Record({
  'text' : IDL.Text,
  'timestamp' : IDL.Nat,
});
export const Chapter = IDL.Record({
  'title' : IDL.Text,
  'summary' : IDL.Text,
  'timestamp' : IDL.Nat,
});
export const LectureRecord = IDL.Record({
  'id' : LectureId,
  'qa' : IDL.Vec(QA),
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'takeaways' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'summary' : IDL.Text,
  'transcript' : IDL.Vec(TranscriptSegment),
  'tableOfContents' : IDL.Vec(Chapter),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func(
      [LectureId, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Text],
      [],
    ),
  'askQuestion' : IDL.Func(
      [LectureId, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteLecture' : IDL.Func([LectureId], [IDL.Bool], []),
  'downloadNotes' : IDL.Func([LectureId], [IDL.Opt(IDL.Text)], ['query']),
  'getLecture' : IDL.Func([LectureId], [IDL.Opt(LectureRecord)], ['query']),
  'getLectures' : IDL.Func([], [IDL.Vec(LectureRecord)], ['query']),
  'processLecture' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : LectureRecord, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LectureId = IDL.Text;
  const QA = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'createdAt' : IDL.Int,
    'answer' : IDL.Text,
    'timestamp' : IDL.Opt(IDL.Nat),
  });
  const TranscriptSegment = IDL.Record({
    'text' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  const Chapter = IDL.Record({
    'title' : IDL.Text,
    'summary' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  const LectureRecord = IDL.Record({
    'id' : LectureId,
    'qa' : IDL.Vec(QA),
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'takeaways' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'summary' : IDL.Text,
    'transcript' : IDL.Vec(TranscriptSegment),
    'tableOfContents' : IDL.Vec(Chapter),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func(
        [LectureId, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Text],
        [],
      ),
    'askQuestion' : IDL.Func(
        [LectureId, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteLecture' : IDL.Func([LectureId], [IDL.Bool], []),
    'downloadNotes' : IDL.Func([LectureId], [IDL.Opt(IDL.Text)], ['query']),
    'getLecture' : IDL.Func([LectureId], [IDL.Opt(LectureRecord)], ['query']),
    'getLectures' : IDL.Func([], [IDL.Vec(LectureRecord)], ['query']),
    'processLecture' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : LectureRecord, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };