/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TranscriptSegment {
    text: string;
    timestamp: bigint;
}
export interface LectureRecord {
    id: LectureId;
    qa: Array<QA>;
    url: string;
    title: string;
    thumbnailUrl: string;
    takeaways: Array<string>;
    createdAt: bigint;
    summary: string;
    transcript: Array<TranscriptSegment>;
    tableOfContents: Array<Chapter>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface QA {
    id: string;
    question: string;
    createdAt: bigint;
    answer: string;
    timestamp?: bigint;
}
export type LectureId = string;
export interface Chapter {
    title: string;
    summary: string;
    timestamp: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface backendInterface {
    addQuestion(lectureId: LectureId, question: string, timestamp: bigint | null): Promise<string>;
    askQuestion(lectureId: LectureId, question: string, timestamp: bigint | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteLecture(id: LectureId): Promise<boolean>;
    downloadNotes(lectureId: LectureId): Promise<string | null>;
    getLecture(id: LectureId): Promise<LectureRecord | null>;
    getLectures(): Promise<Array<LectureRecord>>;
    processLecture(url: string): Promise<{
        __kind__: "ok";
        ok: LectureRecord;
    } | {
        __kind__: "err";
        err: string;
    }>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { Chapter as _Chapter, LectureId as _LectureId, LectureRecord as _LectureRecord, QA as _QA, TranscriptSegment as _TranscriptSegment } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addQuestion(arg0: LectureId, arg1: string, arg2: bigint | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async askQuestion(arg0: LectureId, arg1: string, arg2: bigint | null): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.askQuestion(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askQuestion(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteLecture(arg0: LectureId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLecture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLecture(arg0);
            return result;
        }
    }
    async downloadNotes(arg0: LectureId): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadNotes(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadNotes(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLecture(arg0: LectureId): Promise<LectureRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLecture(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLecture(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLectures(): Promise<Array<LectureRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLectures();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLectures();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async processLecture(arg0: string): Promise<{
        __kind__: "ok";
        ok: LectureRecord;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.processLecture(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processLecture(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_LectureRecord_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LectureRecord): LectureRecord {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_QA_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QA): QA {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LectureRecord]): LectureRecord | null {
    return value.length === 0 ? null : from_candid_LectureRecord_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _LectureId;
    qa: Array<_QA>;
    url: string;
    title: string;
    thumbnailUrl: string;
    takeaways: Array<string>;
    createdAt: bigint;
    summary: string;
    transcript: Array<_TranscriptSegment>;
    tableOfContents: Array<_Chapter>;
}): {
    id: LectureId;
    qa: Array<QA>;
    url: string;
    title: string;
    thumbnailUrl: string;
    takeaways: Array<string>;
    createdAt: bigint;
    summary: string;
    transcript: Array<TranscriptSegment>;
    tableOfContents: Array<Chapter>;
} {
    return {
        id: value.id,
        qa: from_candid_vec_n7(_uploadFile, _downloadFile, value.qa),
        url: value.url,
        title: value.title,
        thumbnailUrl: value.thumbnailUrl,
        takeaways: value.takeaways,
        createdAt: value.createdAt,
        summary: value.summary,
        transcript: value.transcript,
        tableOfContents: value.tableOfContents
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    question: string;
    createdAt: bigint;
    answer: string;
    timestamp: [] | [bigint];
}): {
    id: string;
    question: string;
    createdAt: bigint;
    answer: string;
    timestamp?: bigint;
} {
    return {
        id: value.id,
        question: value.question,
        createdAt: value.createdAt,
        answer: value.answer,
        timestamp: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.timestamp))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _LectureRecord;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: LectureRecord;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_LectureRecord_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LectureRecord>): Array<LectureRecord> {
    return value.map((x)=>from_candid_LectureRecord_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QA>): Array<QA> {
    return value.map((x)=>from_candid_QA_n8(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
